### ISSUE TITLE
[Feature Request] Port to Godot 4

### ISSUE THREAD

**Issue by ssj17vegeta** [AliYil/TranslationsFromJson#1]
Hello and thanks a lot for this awesome addon ! :)

Would be a blast if it got ported to Godot 4 (seems quite a few API changes occurred).

**Comment by AliYil** [comment]
Thank you too! :)

I'll look into porting to Godot 4 when I find the time.

**Comment by AliYil** [comment]
Check out the master branch. It should be working on 4.x. For 3.x, I seperated the old 3.x code into it's own branch.

If you encounter a problem, please open an issue! :)

**Comment by ssj17vegeta** [comment]
Works great, thanks a bunch ! Thanks for your blazing-fast answer and correction :+1:
